############################ Musicians #################################
### Create an Musician
POST http://localhost:4444/api/Musicians HTTP/1.1
content-type: application/json

{
    "firstName": "helloooooo",
    "lastName": "asdfdsf",
    "birthdate": "2020-01-01",
    "email": "abc@dabcd.com",
    "phoneNumber": 2022472839,
    "street": "22 go",
    "city": "Chicago",
    "state": "HI",
    "zip": 19283,
    "inEnsemble": 0,
    "active": 1
}

### see if adding a musician worked
GET http://localhost:4444/api/Musicians HTTP/1.1



### edit a musician
PUT  http://localhost:4444/api/Musicians/1 HTTP/1.1
content-type: application/json

{
    "firstName": "adfdf",
    "lastName": "asdf",
    "birthdate": "2020-01-01",
    "email": "abc@dabcd.com",
    "phoneNumber": 2022472839,
    "street": "22 Chicago",
    "city": "Chicago",
    "state": "HI",
    "zip": 19283,
    "inEnsemble": 0,
    "active": 1,
    "musicianID": 1
}
### Delete from Musicians (might need to change :id)
DELETE http://localhost:4444/api/Musicians/4 HTTP/1.1

############################ Instruments #################################


### Create an instrument
POST http://localhost:4444/api/Instruments HTTP/1.1
content-type: application/json

{
    "name":"Tambourin"
}

### see if adding an instrument worked
GET http://localhost:4444/api/Instruments HTTP/1.1



### edit an instrument
PUT  http://localhost:4444/api/Instruments/4 HTTP/1.1
content-type: application/json

{
    "name":"Harpsichord"
}
### delete from Instruments
DELETE http://localhost:4444/api/Instruments/4 HTTP/1.1




############################ Venues #################################

### Create a venue
POST http://localhost:4444/api/Venues HTTP/1.1
content-type: application/json

{
    "capacity": 21323,
    "name": "Tomato Theatre",
    "street": "22 St",
    "city": "Nowhere",
    "state": "MA",
    "zip": 2124
  }

### see if adding an venue worked
GET http://localhost:4444/api/Venues HTTP/1.1



### edit an instrument
PUT  http://localhost:4444/api/Venues/4 HTTP/1.1
content-type: application/json

{
    "capacity": 800,
    "name": "Space Theatre",
    "street": "arg",
    "city": "Houston",
    "state": "MN",
    "zip": 21243
  }
### delete from Instruments
DELETE http://localhost:4444/api/Venues/4 HTTP/1.1

############################ ConcertCycles #################################

### Create a concertcycle
POST http://localhost:4444/api/ConcertCycles HTTP/1.1
content-type: application/json

{
    "concertTitle": "Wherefore art thou",
    "startDate": "2021-03-05",
    "endDate": "2021-03-09",
    "conductorFirstName": "Leo",
    "conductorLastName": "Messi",
    "soloistFirstName": "",
    "soloistLastName": ""
}
### see if adding an venue worked
GET http://localhost:4444/api/ConcertCycles HTTP/1.1



### edit a concertcycle
PUT  http://localhost:4444/api/ConcertCycles/4 HTTP/1.1
content-type: application/json

{
    "concertTitle": "the firebird",
    "startDate": "2021-03-04",
    "endDate": "2022-03-09",
    "conductorFirstName": "Mickey",
    "conductorLastName": "Mouse",
    "soloistFirstName": "Kermit",
    "soloistLastName": "The Frog"
}
### delete from Instruments
DELETE http://localhost:4444/api/ConcertCycles/5 HTTP/1.1
############################ Venues #################################
############################ Venues #################################
############################ Venues #################################
